dist: trusty
language: php
php:
  - 7.3

before_script:
  - composer install --prefer-source --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpcs
  - vendor/bin/phpunit
  - vendor/bin/infection --configuration=infection.json --min-covered-msi=85
  - vendor/bin/psalm
  - vendor/bin/phpstan analyse src --level 3
