dist: trusty
language: php
php:
  - 7.3

before_script:
  - composer install --prefer-source --no-interaction

jobs:
  include:
    - stage: "Quality"
      name: "Run a quality pipeline"
      script:
        - mkdir -p build/logs
        - cp phpcs.xml.dist phpcs.xml
        - cp phpunit.xml.dist phpunit.xml
        - cp infection.json.dist infection.json
        - cp psalm.xml.dist psalm.xml
        - vendor/bin/phpcs
        - vendor/bin/phpunit
        - vendor/bin/infection --configuration=infection.json --min-covered-msi=85
        - vendor/bin/psalm
        - vendor/bin/phpstan analyse src --level 3
